---
title: "Running simulations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running simulations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(HDXtestpkg)
library(ggplot2)
library(tidyverse)
library(BRAIN)

source("phasim1_mbp.R")

proton_mass = 1.007276466

inputSeq = "KITEGKLVIWINGDKGYNGLAEVGKKFEKDTGIKVTVEHPDKLEEKFPQVAATGDGPDIIFWAHDRFGGYAQSGLLAEITPDKAFQDKLYPFTWDAVRYNGKLIAYPIAVEALSLIYNKDLLPNPPKTWEEIPALDKELKAKGKSALMFNLQEPYFTWPLIAADGGYAFKYENGKYDIKDVGVDNAGAKAGLTFLVDLIKNKHMNADTDYSIAEAAFNKGETAMTINGPWAWSNIDTSKVNYGVTVLPTFKGQPSKPFVGVLSAGINAASPNKELAKEFLENYLLTDEGLEAVNKDKPLGAVALKSYEEELAKDPRIAATMENAQKGEIMPNIPQMSAFWYAVRTAVINAASGRQTVDEALKDAQTRITK"

result <- do_simulation(inputSeq, Charge = 3, inputPF = 1, START = 1, END = 10)
result = data.frame(result)
colnames(result) = c("mz", "intensity")

result %>%
  # filter(intensity > 0) %>%
  ggplot(aes(x = mz, ymin = 0, ymax = intensity)) +
  geom_linerange() +
  theme_bw()

useBRAIN(getAtomsFromSeq(substr(inputSeq, 1, 10)))
1185.712/3 + proton_mass

result
```

```{r }
pepinfo(strsplit("KITEGKLVIWINGDKGYNGLAEVGKK", "")[[1]])

sequence = strsplit("KITEGKLVIWINGDKGYNGLAEVGKK", "")[[1]]
AAshort = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "O",
            "P", "Q", "R", "S", "T", "U", "V", "W", "Y")
AAcarbonNum = c(3, 3, 4, 5, 9, 2, 6, 6, 6, 6, 5, 4, 12, 5, 5, 6, 3, 4, 3, 5, 11, 9)
AAnitrogenNum = c(1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 3, 1, 2, 4, 1, 1, 1, 1, 2, 1)
AAoxygenNum = c(1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 2, 2, 1, 1, 1, 2)
AAsulferNum = c(0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
AAmonoMass = c(71.03711, 103.00919, 115.02694, 129.04259, 147.06841, 57.02146,
               137.05891, 113.08406, 128.09496, 113.08406, 131.04049, 114.04293,
               255.15829, 97.05276, 128.05858, 156.10111, 87.03203, 101.04768,
               168.96420, 99.06841, 186.07931, 163.06333)
names(AAcarbonNum) = AAshort
names(AAnitrogenNum) = AAshort
names(AAoxygenNum) = AAshort
names(AAmonoMass) = AAshort
```
```
