// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fbmme_dh
NumericVector fbmme_dh(CharacterVector sequence, double ph, double temperature, String mol_type);
RcppExport SEXP _HDXtestpkg_fbmme_dh(SEXP sequenceSEXP, SEXP phSEXP, SEXP temperatureSEXP, SEXP mol_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< double >::type ph(phSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< String >::type mol_type(mol_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(fbmme_dh(sequence, ph, temperature, mol_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDXtestpkg_fbmme_dh", (DL_FUNC) &_HDXtestpkg_fbmme_dh, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDXtestpkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
