# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fbmme_dh <- function(sequence, ph, temperature, mol_type) {
    .Call(`_HDXtestpkg_fbmme_dh`, sequence, ph, temperature, mol_type)
}

