# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_deuteration_single_timepoint <- function(initial_matrix, time_sequence, hd_probs, dh_probs) {
    .Call(`_powerHDX_get_deuteration_single_timepoint`, initial_matrix, time_sequence, hd_probs, dh_probs)
}

